export const carTypes = [
  { value: "Toyota Corolla", label: "Toyota Corolla", oil: "6.5" },
  { value: "Honda Civic", label: "Honda Civic", oil: "6.8" },
  { value: "BMW X5", label: "BMW X5", oil: "9.8" },
  { value: "Mercedes-Benz C300", label: "Mercedes-Benz C300", oil: "8.5" },
  { value: "Ferrari 488", label: "Ferrari 488", oil: "12.4" },
  { value: "Lamborghini Huracan", label: "Lamborghini Huracan", oil: "13.8" },
  { value: "Nissan Altima", label: "Nissan Altima", oil: "7.5" },
  { value: "Ford Mustang", label: "Ford Mustang", oil: "11.2" },
  { value: "Chevrolet Camaro", label: "Chevrolet Camaro", oil: "10.8" },
  { value: "Audi A4", label: "Audi A4", oil: "7.9" },
  { value: "Porsche 911", label: "Porsche 911", oil: "11.5" },
  { value: "Subaru Outback", label: "Subaru Outback", oil: "8.2" },
  { value: "Hyundai Elantra", label: "Hyundai Elantra", oil: "6.3" },
  { value: "Kia Sportage", label: "Kia Sportage", oil: "7.6" },
  { value: "Volkswagen Golf", label: "Volkswagen Golf", oil: "6.9" },
  { value: "Lexus RX 350", label: "Lexus RX 350", oil: "9.0" },
  { value: "Jeep Wrangler", label: "Jeep Wrangler", oil: "12.1" },
  { value: "Mazda CX-5", label: "Mazda CX-5", oil: "7.8" },
  { value: "Dodge Challenger", label: "Dodge Challenger", oil: "10.5" },
  { value: "Chevrolet Tahoe", label: "Chevrolet Tahoe", oil: "14.2" },
  { value: "Bugatti Chiron", label: "Bugatti Chiron", oil: "22.5" },
  { value: "McLaren P1", label: "McLaren P1", oil: "14.9" },
  { value: "Rolls-Royce Phantom", label: "Rolls-Royce Phantom", oil: "15.8" },
  { value: "Suzuki Swift", label: "Suzuki Swift", oil: "5.9" },
  { value: "Peugeot 208", label: "Peugeot 208", oil: "5.7" },
  { value: "Toyota Hilux", label: "Toyota Hilux", oil: "9.5" },
  { value: "Honda Accord", label: "Honda Accord", oil: "7.2" },
  { value: "Mitsubishi Outlander", label: "Mitsubishi Outlander", oil: "8.7" },
];
